# Generated by Django 4.1 on 2022-08-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvgQuantityAge',
            fields=[
                ('avg_age_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('age_category', models.CharField(blank=True, max_length=100, null=True)),
                ('avg_age_quantity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avg_quantity_age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AvgQuantityVoucher',
            fields=[
                ('avg_voucher_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('voucher', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_voucher_quantity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'avg_quantity_voucher',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BikeStopInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_stop_id', models.TextField(blank=True, null=True)),
                ('bike_stop_code', models.TextField(blank=True, null=True)),
                ('bike_stop_lat', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('bike_stop_lot', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'bike_stop_information',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_category', models.CharField(blank=True, max_length=200, null=True)),
                ('building_detail', models.CharField(blank=True, max_length=200, null=True)),
                ('gugun', models.CharField(blank=True, max_length=200, null=True)),
                ('hangjungdong', models.CharField(blank=True, max_length=200, null=True)),
                ('building_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('bus_stop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('bus_stop_name', models.CharField(blank=True, max_length=200, null=True)),
                ('bus_stop_lat', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('bus_stop_lot', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'bus_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('event_category', models.CharField(blank=True, max_length=200, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('date', models.IntegerField(blank=True, null=True)),
                ('event_addr', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hangjungdong',
            fields=[
                ('hangjungdong_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gugun', models.CharField(blank=True, max_length=50, null=True)),
                ('hangjungdong', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'hangjungdong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MetroStation',
            fields=[
                ('metro_station_id', models.IntegerField(primary_key=True, serialize=False)),
                ('metro_station_name', models.CharField(blank=True, max_length=200, null=True)),
                ('metro_station_category', models.CharField(blank=True, max_length=200, null=True)),
                ('metro_station_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('metro_station_lot', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'metro_station',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OntimeRentalInfo',
            fields=[
                ('ontime_rental_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_stop_code', models.CharField(blank=True, max_length=20, null=True)),
                ('ontime_timestamp', models.DateTimeField()),
                ('holder_amount', models.IntegerField(blank=True, null=True)),
                ('parking_rate', models.IntegerField(blank=True, null=True)),
                ('parking_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ontime_rental_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('population_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('ref_time', models.CharField(blank=True, max_length=5, null=True)),
                ('hangjungdong_id', models.IntegerField(blank=True, null=True)),
                ('number_0_9', models.IntegerField(blank=True, db_column='0_9', null=True)),
                ('number_10_19', models.IntegerField(blank=True, db_column='10_19', null=True)),
                ('number_20_29', models.IntegerField(blank=True, db_column='20_29', null=True)),
                ('number_30_39', models.IntegerField(blank=True, db_column='30_39', null=True)),
                ('number_40_49', models.IntegerField(blank=True, db_column='40_49', null=True)),
                ('number_50_59', models.IntegerField(blank=True, db_column='50_59', null=True)),
                ('number_60_69', models.IntegerField(blank=True, db_column='60_69', null=True)),
                ('number_70_field', models.IntegerField(blank=True, db_column='70_', null=True)),
            ],
            options={
                'db_table': 'population',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentalPerYear',
            fields=[
                ('rental_per_year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('use_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rental_per_year',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentalRecordPerHour',
            fields=[
                ('rental_record_per_hour_id', models.AutoField(primary_key=True, serialize=False)),
                ('ref_date', models.DateField(blank=True, null=True)),
                ('ref_time', models.TimeField(blank=True, null=True)),
                ('voucher', models.CharField(blank=True, max_length=20, null=True)),
                ('age_distribution', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'RENTAL_RECORD_PER_HOUR',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SumQuantityBikeStop',
            fields=[
                ('sum_bike_stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('bike_stop_id', models.IntegerField(blank=True, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sum_quantity_bike_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SumQuantityPerHourStop',
            fields=[
                ('sum_quantity_hour_id', models.AutoField(primary_key=True, serialize=False)),
                ('bike_stop_id', models.IntegerField(blank=True, null=True)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sum_quantity_per_hour_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportationBus',
            fields=[
                ('transportation_bus_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('depart_bus_stop_id', models.IntegerField(blank=True, null=True)),
                ('arrival_bus_stop_id', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('passenger', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transportation_bus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransportationMetro',
            fields=[
                ('transportation_metro_id', models.AutoField(primary_key=True, serialize=False)),
                ('day_of_week', models.CharField(blank=True, max_length=10, null=True)),
                ('depart_metro_station_id', models.IntegerField(blank=True, null=True)),
                ('arrival_metro_station_id', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('passenger', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transportation_metro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_age_id', models.IntegerField()),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=22, null=True)),
                ('age_category', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=100, null=True)),
                ('avg_age_quantity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_id', models.IntegerField()),
                ('building_category', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('building_detail', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('building_count', models.IntegerField(blank=True, null=True)),
                ('gu_dong', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=401, null=True)),
            ],
            options={
                'db_table': 'view_building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hangjungdong_id', models.IntegerField()),
                ('gu_dong', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=151, null=True)),
            ],
            options={
                'db_table': 'view_dong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewDongBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hangjungdong_id', models.IntegerField()),
                ('gu_dong', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=151, null=True)),
                ('building_id', models.IntegerField()),
                ('building_category', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('building_detail', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('building_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_dong_building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewOntimeStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ontime_rental_info_id', models.IntegerField()),
                ('bike_stop_code', models.CharField(blank=True, db_collation='utf8mb4_unicode_ci', max_length=20, null=True)),
                ('ontime_timestamp', models.DateTimeField()),
                ('holder_amount', models.IntegerField(blank=True, null=True)),
                ('parking_rate', models.IntegerField(blank=True, null=True)),
                ('parking_amount', models.IntegerField(blank=True, null=True)),
                ('bike_stop_id', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('bike_stop_lat', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('bike_stop_lot', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'view_ontime_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=16, null=True)),
                ('hangjungdong_id', models.IntegerField(blank=True, null=True)),
                ('number_0_9', models.IntegerField(blank=True, db_column='0_9', null=True)),
                ('number_10_19', models.IntegerField(blank=True, db_column='10_19', null=True)),
                ('number_20_29', models.IntegerField(blank=True, db_column='20_29', null=True)),
                ('number_30_39', models.IntegerField(blank=True, db_column='30_39', null=True)),
                ('number_40_49', models.IntegerField(blank=True, db_column='40_49', null=True)),
                ('number_50_59', models.IntegerField(blank=True, db_column='50_59', null=True)),
                ('number_60_69', models.IntegerField(blank=True, db_column='60_69', null=True)),
                ('number_70_field', models.IntegerField(blank=True, db_column='70_', null=True)),
            ],
            options={
                'db_table': 'view_pop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_quantity_hour_id', models.IntegerField()),
                ('bike_stop_id', models.IntegerField(blank=True, null=True)),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=22, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_sum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSumAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_quantity_hour_id', models.IntegerField()),
                ('bike_stop_id', models.IntegerField(blank=True, null=True)),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=22, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, null=True)),
                ('avg_age_id', models.IntegerField()),
                ('age_category', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=100, null=True)),
                ('avg_age_quantity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_sum_age',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSumAgeStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_quantity_hour_id', models.IntegerField()),
                ('bike_stop_id', models.IntegerField(blank=True, null=True)),
                ('bike_stop_code', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('bike_stop_lat', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('bike_stop_lot', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=22, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, null=True)),
                ('avg_age_id', models.IntegerField()),
                ('age_category', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=100, null=True)),
                ('avg_age_quantity', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_sum_age_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSumPop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=22, null=True)),
                ('hangjungdong_id', models.IntegerField(blank=True, null=True)),
                ('number_0_9', models.IntegerField(blank=True, db_column='0_9', null=True)),
                ('number_10_19', models.IntegerField(blank=True, db_column='10_19', null=True)),
                ('number_20_29', models.IntegerField(blank=True, db_column='20_29', null=True)),
                ('number_30_39', models.IntegerField(blank=True, db_column='30_39', null=True)),
                ('number_40_49', models.IntegerField(blank=True, db_column='40_49', null=True)),
                ('number_50_59', models.IntegerField(blank=True, db_column='50_59', null=True)),
                ('number_60_69', models.IntegerField(blank=True, db_column='60_69', null=True)),
                ('number_70_field', models.IntegerField(blank=True, db_column='70_', null=True)),
                ('sum_quantity_hour_id', models.IntegerField()),
                ('bike_stop_id', models.IntegerField(blank=True, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_sum_pop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSumPopDongBuilding',
            fields=[
                ('id', models.CharField(db_collation='utf8_general_ci', max_length=36, primary_key=True, serialize=False)),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=22, null=True)),
                ('hangjungdong_id', models.IntegerField(blank=True, null=True)),
                ('number_0_9', models.IntegerField(blank=True, db_column='0_9', null=True)),
                ('number_10_19', models.IntegerField(blank=True, db_column='10_19', null=True)),
                ('number_20_29', models.IntegerField(blank=True, db_column='20_29', null=True)),
                ('number_30_39', models.IntegerField(blank=True, db_column='30_39', null=True)),
                ('number_40_49', models.IntegerField(blank=True, db_column='40_49', null=True)),
                ('number_50_59', models.IntegerField(blank=True, db_column='50_59', null=True)),
                ('number_60_69', models.IntegerField(blank=True, db_column='60_69', null=True)),
                ('number_70_field', models.IntegerField(blank=True, db_column='70_', null=True)),
                ('sum_quantity_hour_id', models.IntegerField()),
                ('bike_stop_id', models.IntegerField(blank=True, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, null=True)),
                ('gu_dong', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=151, null=True)),
                ('building_id', models.IntegerField()),
                ('building_category', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('building_detail', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('building_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_sum_pop_dong_building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSumPopDongBuildingWithoutStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=22, null=True)),
                ('hangjungdong_id', models.IntegerField(blank=True, null=True)),
                ('number_0_9', models.IntegerField(blank=True, db_column='0_9', null=True)),
                ('number_10_19', models.IntegerField(blank=True, db_column='10_19', null=True)),
                ('number_20_29', models.IntegerField(blank=True, db_column='20_29', null=True)),
                ('number_30_39', models.IntegerField(blank=True, db_column='30_39', null=True)),
                ('number_40_49', models.IntegerField(blank=True, db_column='40_49', null=True)),
                ('number_50_59', models.IntegerField(blank=True, db_column='50_59', null=True)),
                ('number_60_69', models.IntegerField(blank=True, db_column='60_69', null=True)),
                ('number_70_field', models.IntegerField(blank=True, db_column='70_', null=True)),
                ('gu_dong', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=151, null=True)),
                ('building_category', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('building_detail', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=200, null=True)),
                ('building_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_sum_pop_dong_building_without_stop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewSumPopStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.CharField(blank=True, db_collation='utf8_general_ci', max_length=22, null=True)),
                ('hangjungdong_id', models.IntegerField(blank=True, null=True)),
                ('number_0_9', models.IntegerField(blank=True, db_column='0_9', null=True)),
                ('number_10_19', models.IntegerField(blank=True, db_column='10_19', null=True)),
                ('number_20_29', models.IntegerField(blank=True, db_column='20_29', null=True)),
                ('number_30_39', models.IntegerField(blank=True, db_column='30_39', null=True)),
                ('number_40_49', models.IntegerField(blank=True, db_column='40_49', null=True)),
                ('number_50_59', models.IntegerField(blank=True, db_column='50_59', null=True)),
                ('number_60_69', models.IntegerField(blank=True, db_column='60_69', null=True)),
                ('number_70_field', models.IntegerField(blank=True, db_column='70_', null=True)),
                ('sum_quantity_hour_id', models.IntegerField()),
                ('bike_stop_id', models.IntegerField(blank=True, null=True)),
                ('sum_quantity', models.IntegerField(blank=True, null=True)),
                ('bike_stop_code', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('bike_stop_lat', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('bike_stop_lot', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'view_sum_pop_stop',
                'managed': False,
            },
        ),
    ]
